# Generated by Django 5.2.7 on 2025-10-12 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('concept', models.TextField()),
                ('num_scenes', models.IntegerField()),
                ('creativity_level', models.CharField(choices=[('factual', 'Factual'), ('creative', 'Creative'), ('balanced', 'Balanced')], default='balanced', max_length=20)),
                ('project_type', models.CharField(choices=[('story', 'Story'), ('commercial', 'Commercial')], default='story', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('state_json', models.JSONField()),
            ],
            options={
                'unique_together': {('thread_id', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_type', models.CharField(default='story', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('scene_number', models.IntegerField()),
                ('script', models.TextField()),
                ('characters', models.JSONField(blank=True, default=list)),
                ('product', models.JSONField(blank=True, default=dict, null=True)),
                ('environment', models.TextField(blank=True, default='')),
                ('lighting', models.TextField(blank=True, default='')),
                ('story_context', models.TextField(blank=True)),
                ('image_prompt', models.TextField(blank=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('video', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='RetrivalAPI.project')),
            ],
            options={
                'ordering': ['scene_number'],
                'unique_together': {('project', 'scene_number')},
            },
        ),
    ]
